import jsPDF from "jspdf";

type AnalyzeData = {
  url: string;
  title: string;
  metaDescription: string;
  headings: { h1: string[]; h2: string[]; h3: string[] };
  score: number;
  aiInsights?: {
    summary: string;
    suggestions: string[];
  } | null;
  geoAnalysis?: {
    aiReadinessScore: number;
    entities: string[];
    aiRankingScore: number;
    readinessFactors: string[];
  } | null;
};

export function generateMarkdownReport(data: AnalyzeData): string {
  const timestamp = new Date().toLocaleString();
  
  let markdown = `# OptiGenius Analysis Report\n\n`;
  markdown += `**Generated:** ${timestamp}\n\n`;
  markdown += `**URL:** ${data.url}\n\n`;
  markdown += `---\n\n`;
  
  // SEO Score
  markdown += `## SEO Score: ${data.score}/100\n\n`;
  
  // Basic SEO Elements
  markdown += `## SEO Elements\n\n`;
  markdown += `### Title\n${data.title || "Not found"}\n\n`;
  markdown += `### Meta Description\n${data.metaDescription || "Not found"}\n\n`;
  
  // Headings
  markdown += `### Headings Structure\n\n`;
  if (data.headings.h1.length > 0) {
    markdown += `**H1 Tags (${data.headings.h1.length}):**\n`;
    data.headings.h1.forEach(h => markdown += `- ${h}\n`);
    markdown += `\n`;
  }
  if (data.headings.h2.length > 0) {
    markdown += `**H2 Tags (${data.headings.h2.length}):**\n`;
    data.headings.h2.slice(0, 10).forEach(h => markdown += `- ${h}\n`);
    if (data.headings.h2.length > 10) markdown += `- ... and ${data.headings.h2.length - 10} more\n`;
    markdown += `\n`;
  }
  
  // GEO Analysis
  if (data.geoAnalysis) {
    markdown += `## GEO (Generative Engine Optimization) Analysis\n\n`;
    markdown += `- **AI-Readiness Score:** ${data.geoAnalysis.aiReadinessScore}/100\n`;
    markdown += `- **AI Ranking Prediction:** ${data.geoAnalysis.aiRankingScore}/100\n\n`;
    
    if (data.geoAnalysis.entities.length > 0) {
      markdown += `### Entities Detected\n`;
      data.geoAnalysis.entities.forEach(entity => markdown += `- ${entity}\n`);
      markdown += `\n`;
    }
    
    if (data.geoAnalysis.readinessFactors.length > 0) {
      markdown += `### Key Readiness Factors\n`;
      data.geoAnalysis.readinessFactors.forEach(factor => markdown += `- ${factor}\n`);
      markdown += `\n`;
    }
  }
  
  // AI Insights
  if (data.aiInsights) {
    markdown += `## AI Insights\n\n`;
    markdown += `### Content Summary\n${data.aiInsights.summary}\n\n`;
    
    if (data.aiInsights.suggestions.length > 0) {
      markdown += `### SEO Improvement Suggestions\n`;
      data.aiInsights.suggestions.forEach((suggestion, i) => {
        markdown += `${i + 1}. ${suggestion}\n`;
      });
      markdown += `\n`;
    }
  }
  
  markdown += `---\n\n`;
  markdown += `*Report generated by OptiGenius - AI-Powered SEO & GEO Analysis*\n`;
  
  return markdown;
}

export function downloadMarkdown(data: AnalyzeData) {
  const markdown = generateMarkdownReport(data);
  const blob = new Blob([markdown], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `optigenius-report-${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function generatePDFReport(data: AnalyzeData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let y = 20;
  
  // Helper function to add text with word wrap
  const addText = (text: string, fontSize: number, isBold: boolean = false, color: [number, number, number] = [0, 0, 0]) => {
    doc.setFontSize(fontSize);
    doc.setTextColor(color[0], color[1], color[2]);
    if (isBold) {
      doc.setFont("helvetica", "bold");
    } else {
      doc.setFont("helvetica", "normal");
    }
    
    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach((line: string) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += fontSize * 0.5;
    });
    y += 3;
  };
  
  // Title
  addText("OptiGenius Analysis Report", 20, true, [37, 99, 235]);
  y += 5;
  
  // Metadata
  addText(`Generated: ${new Date().toLocaleString()}`, 10, false, [100, 100, 100]);
  addText(`URL: ${data.url}`, 10, false, [100, 100, 100]);
  y += 5;
  
  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;
  
  // SEO Score
  addText(`SEO Score: ${data.score}/100`, 16, true);
  y += 5;
  
  // SEO Elements
  addText("SEO Elements", 14, true);
  y += 2;
  
  addText("Title:", 11, true);
  addText(data.title || "Not found", 10);
  y += 2;
  
  addText("Meta Description:", 11, true);
  addText(data.metaDescription || "Not found", 10);
  y += 5;
  
  // Headings
  addText("Headings Structure", 12, true);
  if (data.headings.h1.length > 0) {
    addText(`H1 Tags (${data.headings.h1.length}):`, 10, true);
    data.headings.h1.forEach(h => addText(`• ${h}`, 9));
  }
  if (data.headings.h2.length > 0) {
    addText(`H2 Tags (${data.headings.h2.length}):`, 10, true);
    data.headings.h2.slice(0, 5).forEach(h => addText(`• ${h}`, 9));
    if (data.headings.h2.length > 5) {
      addText(`... and ${data.headings.h2.length - 5} more`, 9, false, [100, 100, 100]);
    }
  }
  y += 5;
  
  // GEO Analysis
  if (data.geoAnalysis) {
    addText("GEO Analysis", 14, true, [37, 99, 235]);
    y += 2;
    
    addText(`AI-Readiness Score: ${data.geoAnalysis.aiReadinessScore}/100`, 11);
    addText(`AI Ranking Prediction: ${data.geoAnalysis.aiRankingScore}/100`, 11);
    y += 2;
    
    if (data.geoAnalysis.entities.length > 0) {
      addText("Entities Detected:", 10, true);
      addText(data.geoAnalysis.entities.join(", "), 9);
      y += 2;
    }
    
    if (data.geoAnalysis.readinessFactors.length > 0) {
      addText("Key Readiness Factors:", 10, true);
      data.geoAnalysis.readinessFactors.forEach(factor => addText(`• ${factor}`, 9));
      y += 3;
    }
  }
  
  // AI Insights
  if (data.aiInsights) {
    addText("AI Insights", 14, true, [147, 51, 234]);
    y += 2;
    
    addText("Content Summary:", 11, true);
    addText(data.aiInsights.summary, 10);
    y += 3;
    
    if (data.aiInsights.suggestions.length > 0) {
      addText("SEO Improvement Suggestions:", 11, true);
      data.aiInsights.suggestions.forEach((suggestion, i) => {
        addText(`${i + 1}. ${suggestion}`, 9);
      });
    }
  }
  
  // Footer
  if (y > 250) {
    doc.addPage();
    y = 20;
  }
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Report generated by OptiGenius - AI-Powered SEO & GEO Analysis", margin, 285);
  
  // Download
  doc.save(`optigenius-report-${Date.now()}.pdf`);
}
